export const SERVICES = [
  {
    service_category: 'Manicure',
    service: 'Mani & Pedi',
    time: '30 Min-1 Hour',
    price: '$45',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Manicure',
    time: '20-30 Min',
    price: '$20',
    button: 'Book Now',
    addons: [
      {id: 1, name: 'XL', price: 10, category: 'Diamonds'},
      {id: 2, name: 'L', price: 8, category: 'Diamonds'},
      {id: 3, name: 'M', price: 6, category: 'Diamonds'},
      {id: 4, name: 'S', price: 4, category: 'Diamonds'},
      {id: 5, name: 'XS', price: 2, category: 'Diamonds'},
      {id: 6, name: 'Bling 2 Fingers', price: 7, category: 'Diamonds'},
      {id: 7, name: 'Bling 2 Fingers - Long', price: 10, category: 'Diamonds'},
      {
        id: 8,
        name: 'Swarovski pixie dust caviar 2 fingers',
        price: 18,
        category: 'Diamonds',
      },
      {id: 9, name: 'Lines', price: 4, category: 'Foils'},
      {id: 10, name: 'Flakes - 2 Fingers', price: 4, category: 'Foils'},
      {id: 11, name: 'Leafing - 2 Fingers', price: 4, category: 'Foils'},
      {id: 12, name: 'Glass - 2 Fingers', price: 8, category: 'Foils'},
      {id: 13, name: 'Design - 2 Fingers', price: 10, category: 'Foils'},
      {id: 14, name: 'Stamping - 2 Fingers', price: 12, category: 'Foils'},
    ],
  },

  {
    service_category: 'Manicure',
    service: 'Pedicure',
    time: '20-30 Min',
    price: '$30',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Polish - Hands',
    time: '20-30 Min',
    price: '$10',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Polish - Toes',
    time: '20-30 Min',
    price: '$12',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Parrafin - Hands',
    time: '20-30 Min',
    price: '$10',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Parrafin - Toes',
    time: '20-30 Min',
    price: '$15',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Shellac - Hands Change',
    time: '20-30 Min',
    price: '$20',
    button: 'Book Now',
  },
  {
    service_category: 'Manicure',
    service: 'Shellac - Toes Change',
    time: '20-30 Min',
    price: '$30',
    button: 'Book Now',
  },
  {
    service_category: 'Nail Enhancements',
    service: 'Bio',
    time: '30 Min-1 Hour',
    price: '$45',
    button: 'Book Now',
  },
  {
    service_category: 'Nail Enhancements',
    service: 'Acrylic',
    time: '20-30 Min',
    price: '$20',
    button: 'Book Now',
  },
  {
    service_category: 'Nail Enhancements',
    service: 'Pink & White Solor',
    time: '20-30 Min',
    price: '$30',
    button: 'Book Now',
  },
  {
    service_category: 'Nail Enhancements',
    service: 'UV Gel Powder',
    time: '20-30 Min',
    price: '$10',
    button: 'Book Now',
  },
  {
    service_category: 'Nail Enhancements',
    service: 'Misc',
    time: '20-30 Min',
    price: '$12',
    button: 'Book Now',
  },
  {
    service_category: 'Design',
    service: 'Misc',
    time: '20-30 Min',
    price: '$12',
    button: 'Book Now',
  },
];

//export default SERVICES;
